apiVersion: v1
kind: Config
current-context: minikube
preferences: {}
clusters:
  - name: minikube
    cluster:
      server: https://127.0.0.1:8443
      certificate-authority-data: ZmFrZS1jYS1jZXJ0LWRhdGEtZm9yLW1pbmlrdWJlLXRlc3Rpbmc=
contexts:
  - name: minikube
    context:
      cluster: minikube
      user: minikube
      namespace: default
users:
  - name: minikube
    user:
      client-certificate-data: ZmFrZS1jbGllbnQtY2VydC1kYXRhLWZvci1taW5pa3ViZQ==
      client-key-data: ZmFrZS1jbGllbnQta2V5LWRhdGEtZm9yLW1pbmlrdWJl
